"""Enhanced models

Revision ID: 915545fdbf90
Revises: 
Create Date: 2025-07-29 01:21:39.893402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915545fdbf90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('attendance_educator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('educator_id')

    with op.batch_alter_table('class_subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('class_subjects_educator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'])
        batch_op.drop_column('educator_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('class_subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('educator_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('class_subjects_educator_id_fkey'), 'users', ['educator_id'], ['id'])
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('educator_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_educator_id_fkey'), 'users', ['educator_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
