"""Add Assignment submission score field

Revision ID: db62a9938d76
Revises: 32aab15f4a44
Create Date: 2025-07-28 14:19:12.666904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db62a9938d76'
down_revision: Union[str, Sequence[str], None] = '32aab15f4a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_submissions', 'score')
    # ### end Alembic commands ###
