# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Flask Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'shuleni-backend/**'
  pull_request:
    branches: 
      - 'main'
      - 'kendy-backend'
    paths:
      - 'shuleni-backend/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies from backend requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r shuleni-backend/requirements.txt

    - name: Set PYTHONPATH and run tests
      run: |
        export PYTHONPATH="${{ github.workspace }}/shuleni-backend"
        echo "PYTHONPATH set to: $PYTHONPATH"
        pytest shuleni-backend/tests --tb=short -v
