# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
     - 'shuleni-frontend/**' 
  pull_request:
    branches: [ "main" ]
    paths:
      - 'shuleni-frontend/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version you want to use
          cache: 'npm' 

      - name: Install Dependencies
        working-directory: ./shuleni-frontend
        run: npm install  
        

      - name: Build Project
        working-directory: ./shuleni-frontend
        run: npm run build
      

      - name : Skip Tests
        run: echo "Skipping tests for frontend CI"
